# Generated by Django 3.2.5 on 2022-06-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_size', models.IntegerField()),
                ('rotation_distribution', models.CharField(choices=[('R', 'Random Rotation'), ('C', 'Central Rotation'), ('O', 'Outer Rotation')], default='R', max_length=1)),
                ('rot_proportion', models.FloatField(verbose_name='Rotation proportion')),
                ('angle', models.IntegerField(choices=[(0, '0º'), (1, '90º'), (2, '180º'), (3, '270º')], default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.image')),
            ],
        ),
    ]
