# Generated by Django 3.2.5 on 2022-07-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20220723_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='angle',
            field=models.IntegerField(choices=[(0, '0º'), (1, '90º'), (2, '180º'), (3, '270º')], default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='rot_proportion',
            field=models.FloatField(default=0, verbose_name='Rotation proportion'),
        ),
        migrations.AddField(
            model_name='image',
            name='rotation_distribution',
            field=models.CharField(choices=[('R', 'Random Rotation'), ('C', 'Central Rotation'), ('O', 'Outer Rotation')], default='R', max_length=1),
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
