# Generated by Django 3.2.5 on 2022-07-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20220724_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('dice_score', models.FloatField()),
                ('og_dice_score', models.FloatField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.image')),
            ],
        ),
    ]
