# Generated by Django 3.2.5 on 2022-07-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='image',
            field=models.FileField(default=None, upload_to='images/'),
        ),
    ]
